Repository 4-mul-meong/backend-comment, pull requests merged in 2024-11, with the labels that each got.

#3 [🚀 Comment] CI/CD 환경 구축
  .github/workflows/cicd.yaml
  Dockerfile
  build.gradle
  src/main/java/com/mulmeong/comment/CommentApplication.java
  src/test/java/com/mulmeong/comment/CommentApplicationTests.java
Labels: 👷 chore, 🚀 deploy

#9 [🔀 Comment] 쇼츠 댓글 기능 구현
  build.gradle
  src/main/java/com/mulmeong/comment/CommentApplication.java
  src/main/java/com/mulmeong/comment/application/ShortsCommentService.java
  src/main/java/com/mulmeong/comment/application/ShortsCommentServiceImpl.java
  src/main/java/com/mulmeong/comment/common/config/QueryDslConfig.java
  src/main/java/com/mulmeong/comment/common/config/SwaggerConfig.java
  src/main/java/com/mulmeong/comment/common/entity/BaseEntity.java
  src/main/java/com/mulmeong/comment/common/exception/BaseException.java
  src/main/java/com/mulmeong/comment/common/exception/GlobalExceptionHandler.java
  src/main/java/com/mulmeong/comment/common/response/BaseResponse.java
  src/main/java/com/mulmeong/comment/common/response/BaseResponseStatus.java
  src/main/java/com/mulmeong/comment/common/utils/CursorPage.java
  src/main/java/com/mulmeong/comment/dto/in/ShortsCommentDeleteDto.java
  src/main/java/com/mulmeong/comment/dto/in/ShortsCommentRequestDto.java
  src/main/java/com/mulmeong/comment/dto/in/ShortsCommentUpdateDto.java
  src/main/java/com/mulmeong/comment/dto/out/ShortsCommentResponseDto.java
  src/main/java/com/mulmeong/comment/entity/ShortsComment.java
  src/main/java/com/mulmeong/comment/infrasturcture/ShortsCommentRepository.java
  src/main/java/com/mulmeong/comment/infrasturcture/ShortsCommentRepositoryCustom.java
  src/main/java/com/mulmeong/comment/infrasturcture/ShortsCommentRepositoryCustomImpl.java
  src/main/java/com/mulmeong/comment/presentation/ShortsCommentController.java
  src/main/java/com/mulmeong/comment/vo/in/ShortsCommentRequestVo.java
  src/main/java/com/mulmeong/comment/vo/in/ShortsCommentUpdateVo.java
  src/main/java/com/mulmeong/comment/vo/out/ShortsCommentResponseVo.java
Labels: ✨ enhancement

#7 [🔀 Comment] 피드 댓글 기능 구현
  src/main/java/com/mulmeong/comment/CommentApplication.java
  src/main/java/com/mulmeong/comment/application/FeedCommentService.java
  src/main/java/com/mulmeong/comment/application/FeedCommentServiceImpl.java
  src/main/java/com/mulmeong/comment/common/config/SwaggerConfig.java
  src/main/java/com/mulmeong/comment/common/exception/GlobalExceptionHandler.java
  src/main/java/com/mulmeong/comment/common/response/BaseResponse.java
  src/main/java/com/mulmeong/comment/common/response/BaseResponseStatus.java
  src/main/java/com/mulmeong/comment/common/utils/CursorPage.java
  src/main/java/com/mulmeong/comment/dto/in/FeedCommentDeleteDto.java
  src/main/java/com/mulmeong/comment/dto/in/FeedCommentRequestDto.java
  src/main/java/com/mulmeong/comment/dto/in/FeedCommentUpdateDto.java
  src/main/java/com/mulmeong/comment/dto/out/FeedCommentResponseDto.java
  src/main/java/com/mulmeong/comment/entity/FeedComment.java
  src/main/java/com/mulmeong/comment/infrastructure/FeedCommentRepository.java
  src/main/java/com/mulmeong/comment/infrastructure/FeedCommentRepositoryCustom.java
  src/main/java/com/mulmeong/comment/infrastructure/FeedCommentRepositoryCustomImpl.java
  src/main/java/com/mulmeong/comment/presentation/FeedCommentController.java
  src/main/java/com/mulmeong/comment/vo/in/FeedCommentRequestVo.java
  src/main/java/com/mulmeong/comment/vo/in/FeedCommentUpdateVo.java
  src/main/java/com/mulmeong/comment/vo/out/FeedCommentResponseVo.java
Labels: ✨ enhancement

#8 [🔀 Comment] 피드 대댓글 기능 구현
  src/main/java/com/mulmeong/comment/application/FeedRecommentService.java
  src/main/java/com/mulmeong/comment/application/FeedRecommentServiceImpl.java
  src/main/java/com/mulmeong/comment/common/response/BaseResponseStatus.java
  src/main/java/com/mulmeong/comment/common/utils/CursorPage.java
  src/main/java/com/mulmeong/comment/dto/in/FeedRecommentRequestDto.java
  src/main/java/com/mulmeong/comment/dto/in/FeedRecommentUpdateDto.java
  src/main/java/com/mulmeong/comment/dto/out/FeedRecommentResponseDto.java
  src/main/java/com/mulmeong/comment/entity/FeedRecomment.java
  src/main/java/com/mulmeong/comment/infrastructure/FeedRecommentRepository.java
  src/main/java/com/mulmeong/comment/infrastructure/FeedRecommentRepositoryCustom.java
  src/main/java/com/mulmeong/comment/infrastructure/FeedRecommentRepositoryCustomImpl.java
  src/main/java/com/mulmeong/comment/presentation/FeedRecommentController.java
  src/main/java/com/mulmeong/comment/vo/in/FeedRecommentRequestVo.java
  src/main/java/com/mulmeong/comment/vo/in/FeedRecommentUpdateVo.java
  src/main/java/com/mulmeong/comment/vo/out/FeedRecommentResponseVo.java
Labels: ✨ enhancement

#10 [🔀 Comment] 쇼츠 대댓글 기능 구현
  src/main/java/com/mulmeong/comment/application/ShortsRecommentService.java
  src/main/java/com/mulmeong/comment/application/ShortsRecommentServiceImpl.java
  src/main/java/com/mulmeong/comment/common/utils/CursorPage.java
  src/main/java/com/mulmeong/comment/dto/in/ShortsRecommentRequestDto.java
  src/main/java/com/mulmeong/comment/dto/in/ShortsRecommentUpdateDto.java
  src/main/java/com/mulmeong/comment/dto/out/ShortsRecommentResponseDto.java
  src/main/java/com/mulmeong/comment/entity/ShortsRecomment.java
  src/main/java/com/mulmeong/comment/infrastructure/ShortsRecommentRepository.java
  src/main/java/com/mulmeong/comment/infrastructure/ShortsRecommentRepositoryCustom.java
  src/main/java/com/mulmeong/comment/infrastructure/ShortsRecommentRepositoryCustomImpl.java
  src/main/java/com/mulmeong/comment/presentation/ShortsRecommentController.java
  src/main/java/com/mulmeong/comment/vo/in/ShortsRecommentRequestVo.java
  src/main/java/com/mulmeong/comment/vo/in/ShortsRecommentUpdateVo.java
  src/main/java/com/mulmeong/comment/vo/out/ShortsRecommentResponseVo.java
Labels: ✨ enhancement

#11 [🚑️ Comment] develop push 에러 Resolve
  src/main/java/com/mulmeong/comment/application/FeedCommentService.java
  src/main/java/com/mulmeong/comment/application/FeedCommentServiceImpl.java
  src/main/java/com/mulmeong/comment/application/FeedRecommentService.java
  src/main/java/com/mulmeong/comment/application/FeedRecommentServiceImpl.java
  src/main/java/com/mulmeong/comment/application/ShortsCommentService.java
  src/main/java/com/mulmeong/comment/application/ShortsCommentServiceImpl.java
  src/main/java/com/mulmeong/comment/application/ShortsRecommentService.java
  src/main/java/com/mulmeong/comment/application/ShortsRecommentServiceImpl.java
  src/main/java/com/mulmeong/comment/common/response/BaseResponseStatus.java
  src/main/java/com/mulmeong/comment/dto/in/FeedRecommentRequestDto.java
  src/main/java/com/mulmeong/comment/infrastructure/ShortsCommentRepository.java
  src/main/java/com/mulmeong/comment/infrastructure/ShortsCommentRepositoryCustom.java
  src/main/java/com/mulmeong/comment/infrastructure/ShortsCommentRepositoryCustomImpl.java
  src/main/java/com/mulmeong/comment/presentation/FeedCommentController.java
  src/main/java/com/mulmeong/comment/presentation/FeedRecommentController.java
  src/main/java/com/mulmeong/comment/presentation/ShortsCommentController.java
  src/main/java/com/mulmeong/comment/presentation/ShortsRecommentController.java
Labels: 🚑️ hotfix

#16 [🚑️ Comment] Docker network 연결
  .github/workflows/cicd.yaml
  Dockerfile
  src/test/java/com/mulmeong/comment/CommentApplicationTests.java
Labels: 🐛 bug, 👷 chore, 🚀 deploy, 🚑️ hotfix

#22 [🚑️ Comment] Timezone 에러 Resolve
  Dockerfile
Labels: 🐛 bug, 👷 chore, 🚀 deploy, 🚑️ hotfix

#23 [🔀 Comment] 댓글 kafka 기능 구현
  src/main/java/com/mulmeong/comment/application/EventPublisher.java
  src/main/java/com/mulmeong/comment/application/FeedCommentService.java
  src/main/java/com/mulmeong/comment/application/FeedCommentServiceImpl.java
  src/main/java/com/mulmeong/comment/application/FeedRecommentService.java
  src/main/java/com/mulmeong/comment/application/FeedRecommentServiceImpl.java
  src/main/java/com/mulmeong/comment/application/KafkaProducer.java
  src/main/java/com/mulmeong/comment/application/ShortsCommentService.java
  src/main/java/com/mulmeong/comment/application/ShortsCommentServiceImpl.java
  src/main/java/com/mulmeong/comment/application/ShortsRecommentService.java
  src/main/java/com/mulmeong/comment/application/ShortsRecommentServiceImpl.java
  src/main/java/com/mulmeong/comment/common/config/KafkaConfig.java
  src/main/java/com/mulmeong/comment/common/health/HealthCheckController.java
  src/main/java/com/mulmeong/comment/dto/in/ShortsCommentUpdateDto.java
  src/main/java/com/mulmeong/comment/dto/kafka/FeedCommentMessageDto.java
  src/main/java/com/mulmeong/comment/dto/out/FeedCommentResponseDto.java
  src/main/java/com/mulmeong/comment/dto/out/ShortsCommentResponseDto.java
  src/main/java/com/mulmeong/comment/infrastructure/FeedCommentRepositoryCustom.java
  src/main/java/com/mulmeong/comment/infrastructure/FeedCommentRepositoryCustomImpl.java
  src/main/java/com/mulmeong/comment/infrastructure/FeedRecommentRepositoryCustom.java
  src/main/java/com/mulmeong/comment/infrastructure/FeedRecommentRepositoryCustomImpl.java
  src/main/java/com/mulmeong/comment/infrastructure/ShortsCommentRepositoryCustom.java
  src/main/java/com/mulmeong/comment/infrastructure/ShortsCommentRepositoryCustomImpl.java
  src/main/java/com/mulmeong/comment/infrastructure/ShortsRecommentRepositoryCustom.java
  src/main/java/com/mulmeong/comment/infrastructure/ShortsRecommentRepositoryCustomImpl.java
  src/main/java/com/mulmeong/comment/presentation/FeedCommentController.java
  src/main/java/com/mulmeong/comment/presentation/FeedRecommentController.java
  src/main/java/com/mulmeong/comment/presentation/ShortsCommentAuthController.java
  src/main/java/com/mulmeong/comment/presentation/ShortsCommentController.java
  src/main/java/com/mulmeong/comment/presentation/ShortsRecommentController.java
  src/main/java/com/mulmeong/comment/vo/out/FeedCommentResponseVo.java
  src/main/java/com/mulmeong/comment/vo/out/ShortsCommentResponseVo.java
  src/main/java/com/mulmeong/event/FeedCommentCreateEvent.java
  src/main/java/com/mulmeong/event/FeedCommentDeleteEvent.java
  src/main/java/com/mulmeong/event/FeedCommentUpdateEvent.java
  src/main/java/com/mulmeong/event/FeedRecommentCreateEvent.java
  src/main/java/com/mulmeong/event/FeedRecommentDeleteEvent.java
  src/main/java/com/mulmeong/event/FeedRecommentUpdateEvent.java
  src/main/java/com/mulmeong/event/ShortsCommentCreateEvent.java
  src/main/java/com/mulmeong/event/ShortsCommentDeleteEvent.java
  src/main/java/com/mulmeong/event/ShortsCommentUpdateEvent.java
  src/main/java/com/mulmeong/event/ShortsRecommentCreateEvent.java
  src/main/java/com/mulmeong/event/ShortsRecommentDeleteEvent.java
  src/main/java/com/mulmeong/event/ShortsRecommentUpdateEvent.java
Labels: ✨ enhancement

#25 [🔀 Comment] Config-server 연동 및 kafka 수정
  build.gradle
  src/main/java/com/mulmeong/comment/CommentApplication.java
  src/main/java/com/mulmeong/comment/application/EventPublisher.java
  src/main/java/com/mulmeong/comment/application/FeedCommentServiceImpl.java
  src/main/java/com/mulmeong/comment/application/FeedRecommentServiceImpl.java
  src/main/java/com/mulmeong/comment/application/ShortsCommentServiceImpl.java
  src/main/java/com/mulmeong/comment/application/ShortsRecommentServiceImpl.java
  src/main/java/com/mulmeong/event/comment/FeedCommentCreateEvent.java
  src/main/java/com/mulmeong/event/comment/FeedCommentDeleteEvent.java
  src/main/java/com/mulmeong/event/comment/FeedCommentUpdateEvent.java
  src/main/java/com/mulmeong/event/comment/FeedRecommentCreateEvent.java
  src/main/java/com/mulmeong/event/comment/FeedRecommentDeleteEvent.java
  src/main/java/com/mulmeong/event/comment/FeedRecommentUpdateEvent.java
  src/main/java/com/mulmeong/event/comment/ShortsCommentCreateEvent.java
  src/main/java/com/mulmeong/event/comment/ShortsCommentDeleteEvent.java
  src/main/java/com/mulmeong/event/comment/ShortsCommentUpdateEvent.java
  src/main/java/com/mulmeong/event/comment/ShortsRecommentCreateEvent.java
  src/main/java/com/mulmeong/event/comment/ShortsRecommentDeleteEvent.java
  src/main/java/com/mulmeong/event/comment/ShortsRecommentUpdateEvent.java
Labels: ✨ enhancement

#27 [🔀 Comment] 댓글 수정
  src/main/java/com/mulmeong/comment/application/FeedCommentService.java
  src/main/java/com/mulmeong/comment/application/FeedCommentServiceImpl.java
  src/main/java/com/mulmeong/comment/application/FeedRecommentService.java
  src/main/java/com/mulmeong/comment/application/FeedRecommentServiceImpl.java
  src/main/java/com/mulmeong/comment/application/ShortsCommentService.java
  src/main/java/com/mulmeong/comment/application/ShortsCommentServiceImpl.java
  src/main/java/com/mulmeong/comment/application/ShortsRecommentService.java
  src/main/java/com/mulmeong/comment/application/ShortsRecommentServiceImpl.java
  src/main/java/com/mulmeong/comment/dto/in/FeedCommentDeleteDto.java
  src/main/java/com/mulmeong/comment/dto/in/FeedCommentRequestDto.java
  src/main/java/com/mulmeong/comment/dto/in/FeedCommentUpdateDto.java
  src/main/java/com/mulmeong/comment/dto/in/ShortsCommentDeleteDto.java
  src/main/java/com/mulmeong/comment/dto/in/ShortsCommentRequestDto.java
  src/main/java/com/mulmeong/comment/dto/in/ShortsCommentUpdateDto.java
  src/main/java/com/mulmeong/comment/dto/out/FeedCommentResponseDto.java
  src/main/java/com/mulmeong/comment/dto/out/ShortsCommentResponseDto.java
  src/main/java/com/mulmeong/comment/entity/FeedComment.java
  src/main/java/com/mulmeong/comment/entity/ShortsComment.java
  src/main/java/com/mulmeong/comment/entity/ShortsRecomment.java
  src/main/java/com/mulmeong/comment/infrastructure/FeedCommentRepository.java
  src/main/java/com/mulmeong/comment/infrastructure/FeedRecommentRepository.java
  src/main/java/com/mulmeong/comment/infrastructure/ShortsCommentRepository.java
  src/main/java/com/mulmeong/comment/infrastructure/ShortsRecommentRepository.java
  src/main/java/com/mulmeong/comment/presentation/FeedCommentAuthController.java
  src/main/java/com/mulmeong/comment/presentation/FeedRecommentAuthController.java
  src/main/java/com/mulmeong/comment/presentation/ShortsCommentAuthController.java
  src/main/java/com/mulmeong/comment/presentation/ShortsRecommentAuthController.java
  src/main/java/com/mulmeong/comment/vo/out/FeedCommentResponseVo.java
  src/main/java/com/mulmeong/comment/vo/out/ShortsCommentResponseVo.java
  src/main/java/com/mulmeong/event/comment/FeedCommentCreateEvent.java
  src/main/java/com/mulmeong/event/comment/FeedCommentDeleteEvent.java
  src/main/java/com/mulmeong/event/comment/FeedRecommentCreateEvent.java
  src/main/java/com/mulmeong/event/comment/ShortsCommentCreateEvent.java
  src/main/java/com/mulmeong/event/comment/ShortsCommentDeleteEvent.java
  src/main/java/com/mulmeong/event/comment/ShortsRecommentCreateEvent.java
Labels: ✨ enhancement
